### ISSUE TITLE
Interface test for cos_agent v0 failed.

### ISSUE THREAD

**Issue by benhoyt** [canonical/charm-relation-interfaces#192]
Tests for interface cos_agent v0 failed.

## Provider

- zookeeper: False
- kafka: False

See the workflow https://github.com/canonical/charm-relation-interfaces/actions/runs/11713777734 for more detail.

@mmkay, @Abuelodelanada, @simskij, @dstathis, @PietroPasotti, @michaeldmitry, @lucabello, @ca-scribner, @IbraAoad, @sed-i, @MichaelThamm

**Comment by benhoyt** [comment]
Tests for interface cos_agent v0 failed.

## Provider

- zookeeper: False
- kafka: False

See the workflow https://github.com/canonical/charm-relation-interfaces/actions/runs/11769735758 for more detail.

@mmkay, @Abuelodelanada, @simskij, @dstathis, @PietroPasotti, @michaeldmitry, @lucabello, @ca-scribner, @IbraAoad, @sed-i, @MichaelThamm

**Comment by benhoyt** [comment]
Oh actually, I was mistaken. How this currently runs is that the test script always passes (green), even if one of the relation tests fails. We intend to improve this, but for now, here is the failure from the log:

```
...
INFO:root:Running tests for interface: cos_agent
INFO:root:Running tests for version: v0
INFO:root:Running tests for role: provider
INFO:root:Running 4 cos_agent interface tests on: ['zookeeper', 'kafka']...
INFO:root:Running tests for cos_agent
INFO:root:Running tests for charm: zookeeper
INFO:root:Preparing testing environment for: zookeeper
INFO:root:Cloning: zookeeper from (https://github.com/canonical/zookeeper-operator@main)
INFO:root:Preparing venv for /tmp/charm-relation-interfaces-tests/zookeeper
INFO:root:Installing dependencies in venv for /tmp/charm-relation-interfaces-tests/zookeeper
INFO:root:Installed anyio==4.6.2.post1 ; python_version >= "3.10" and python_version < "4.0"
boto3-stubs[s3]==1.35.40 ; python_version >= "3.10" and python_version < "4.0"
boto3==1.35.40 ; python_version >= "3.10" and python_version < "4.0"
botocore-stubs==1.35.40 ; python_version >= "3.10" and python_version < "4.0"
botocore==1.35.40 ; python_version >= "3.10" and python_version < "4.0"
certifi==2024.8.30 ; python_version >= "3.10" and python_version < "4.0"
cffi==1.17.1 ; python_version >= "3.10" and python_version < "4.0" and platform_python_implementation != "PyPy"
cosl==0.0.41 ; python_version >= "3.10" and python_version < "4.0"
cryptography==43.0.1 ; python_version >= "3.10" and python_version < "4.0"
exceptiongroup==1.2.2 ; python_version >= "3.10" and python_version < "3.11"
h11==0.14.0 ; python_version >= "3.10" and python_version < "4.0"
httpcore==1.0.6 ; python_version >= "3.10" and python_version < "4.0"
httpx==0.27.2 ; python_version >= "3.10" and python_version < "4.0"
idna==3.10 ; python_version >= "3.10" and python_version < "4.0"
jmespath==1.0.1 ; python_version >= "3.10" and python_version < "4.0"
kazoo==2.9.0 ; python_version >= "3.10" and python_version < "4.0"
lightkube-models==1.31.1.8 ; python_version >= "3.10" and python_version < "4.0"
lightkube==0.15.4 ; python_version >= "3.10" and python_version < "4.0"
markdown-it-py==3.0.0 ; python_version >= "3.10" and python_version < "4.0"
mdurl==0.1.2 ; python_version >= "3.10" and python_version < "4.0"
mypy-boto3-s3==1.35.32 ; python_version >= "3.10" and python_version < "4.0"
ops==2.17.0 ; python_version >= "3.10" and python_version < "4.0"
pure-sasl==0.6.2 ; python_version >= "3.10" and python_version < "4.0"
pycparser==2.22 ; python_version >= "3.10" and python_version < "4.0" and platform_python_implementation != "PyPy"
pydantic==1.10.18 ; python_version >= "3.10" and python_version < "4.0"
pygments==2.18.0 ; python_version >= "3.10" and python_version < "4.0"
pyopenssl==24.2.1 ; python_version >= "3.10" and python_version < "4.0"
python-dateutil==2.9.0.post0 ; python_version >= "3.10" and python_version < "4.0"
pyyaml==6.0.2 ; python_version >= "3.10" and python_version < "4.0"
rich==13.9.2 ; python_version >= "3.10" and python_version < "4.0"
rpds-py==0.18.1 ; python_version >= "3.10" and python_version < "4.0"
s3transfer==0.10.3 ; python_version >= "3.10" and python_version < "4.0"
six==1.16.0 ; python_version >= "3.10" and python_version < "4.0"
sniffio==1.3.1 ; python_version >= "3.10" and python_version < "4.0"
tenacity==9.0.0 ; python_version >= "3.10" and python_version < "4.0"
types-awscrt==0.22.0 ; python_version >= "3.10" and python_version < "4.0"
types-s3transfer==0.10.3 ; python_version >= "3.10" and python_version < "4.0"
typing-extensions==4.12.2 ; python_version >= "3.10" and python_version < "4.0"
urllib3==2.2.3 ; python_version >= "3.10" and python_version < "4.0"
websocket-client==1.8.0 ; python_version >= "3.10" and python_version < "4.0"

WARNING:root:test setup failed for zookeeper cos_agent provider
Traceback (most recent call last):
  File "/home/runner/work/charm-relation-interfaces/charm-relation-interfaces/run_matrix.py", line 218, in _test_charm
    charm_path, test_path = _prepare_repo(
  File "/home/runner/work/charm-relation-interfaces/charm-relation-interfaces/run_matrix.py", line 98, in _prepare_repo
    raise SetupError(f"fixture missing for charm {charm_config.name}")
SetupError: fixture missing for charm zookeeper
INFO:root:Result: FAILED
INFO:root:Running tests for charm: kafka
INFO:root:Preparing testing environment for: kafka
INFO:root:Cloning: kafka from (https://github.com/canonical/kafka-operator@main)
INFO:root:Preparing venv for /tmp/charm-relation-interfaces-tests/kafka
INFO:root:Installing dependencies in venv for /tmp/charm-relation-interfaces-tests/kafka
INFO:root:Installed anyio==4.5.2 ; python_version >= "3.8" and python_version < "4.0"
attrs==24.2.0 ; python_version >= "3.8" and python_version < "4.0"
certifi==2024.8.30 ; python_version >= "3.8" and python_version < "4.0"
cffi==1.17.1 ; python_version >= "3.8" and python_version < "4.0" and platform_python_implementation != "PyPy"
charset-normalizer==3.4.0 ; python_version >= "3.8" and python_version < "4.0"
cosl==0.0.24 ; python_version >= "3.8" and python_version < "4.0"
cryptography==43.0.1 ; python_version >= "3.8" and python_version < "4.0"
exceptiongroup==1.2.2 ; python_version >= "3.8" and python_version < "3.11"
h11==0.14.0 ; python_version >= "3.8" and python_version < "4.0"
httpcore==1.0.6 ; python_version >= "3.8" and python_version < "4.0"
httpx==0.27.2 ; python_version >= "3.8" and python_version < "4.0"
idna==3.10 ; python_version >= "3.8" and python_version < "4.0"
importlib-resources==6.4.5 ; python_version >= "3.8" and python_version < "3.9"
jsonschema-specifications==2023.12.1 ; python_version >= "3.8" and python_version < "4.0"
jsonschema==4.23.0 ; python_version >= "3.8" and python_version < "4.0"
kazoo==2.10.0 ; python_version >= "3.8" and python_version < "4.0"
lightkube-models==1.31.1.8 ; python_version >= "3.8" and python_version < "4.0"
lightkube==0.15.0 ; python_version >= "3.8" and python_version < "4.0"
ops==2.17.0 ; python_version >= "3.8" and python_version < "4.0"
pkgutil-resolve-name==1.3.10 ; python_version >= "3.8" and python_version < "3.9"
pure-sasl==0.6.2 ; python_version >= "3.8" and python_version < "4.0"
pycparser==2.22 ; python_version >= "3.8" and python_version < "4.0" and platform_python_implementation != "PyPy"
pydantic==1.10.18 ; python_version >= "3.8" and python_version < "4.0"
pyyaml==6.0.2 ; python_version >= "3.8" and python_version < "4.0"
referencing==0.35.1 ; python_version >= "3.8" and python_version < "4.0"
requests==2.32.3 ; python_version >= "3.8" and python_version < "4.0"
rpds-py==0.18.1 ; python_version >= "3.8" and python_version < "4.0"
sniffio==1.3.1 ; python_version >= "3.8" and python_version < "4.0"
tenacity==9.0.0 ; python_version >= "3.8" and python_version < "4.0"
typing-extensions==4.12.2 ; python_version >= "3.8" and python_version < "4.0"
urllib3==2.2.3 ; python_version >= "3.8" and python_version < "4.0"
websocket-client==1.8.0 ; python_version >= "3.8" and python_version < "4.0"
zipp==3.20.2 ; python_version >= "3.8" and python_version < "3.9"

WARNING:root:test setup failed for kafka cos_agent provider
Traceback (most recent call last):
  File "/home/runner/work/charm-relation-interfaces/charm-relation-interfaces/run_matrix.py", line 218, in _test_charm
    charm_path, test_path = _prepare_repo(
  File "/home/runner/work/charm-relation-interfaces/charm-relation-interfaces/run_matrix.py", line 98, in _prepare_repo
    raise SetupError(f"fixture missing for charm {charm_config.name}")
SetupError: fixture missing for charm kafka
INFO:root:Result: FAILED
...
```
